# Render deployment configuration
services:
  - type: web
    name: ai-research-assistant
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: PORT
        generateValue: true
    healthCheckPath: /health